-- ============================================================================
-- VOICEVAULT SAVED LISTS & SONGS - TABLES, RLS & INDEXES
-- ============================================================================
-- Adds the "In Range" list and custom saved-lists feature.
-- After a user passes "Sing This!", they're prompted to add the song to their
-- "In Range" list (auto-created on first use) or any other custom list.
-- Date: 2026-08-07
-- Safe to run: idempotent design (IF NOT EXISTS / CREATE OR REPLACE)
-- Security:
--   - RLS enabled on both tables; users can only access their own rows
--   - Users can INSERT, SELECT, UPDATE, DELETE their own data
-- ============================================================================

-- ============================================================================
-- TABLE: saved_lists
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.saved_lists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  icon TEXT NOT NULL DEFAULT 'list' CHECK (icon IS NULL OR char_length(icon) <= 50),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Deduplicate existing rows before adding the unique constraint.
-- Keeps the row with the lowest id per (name, user_id) group.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname = 'public'
      AND tablename = 'saved_lists'
      AND indexname = 'idx_saved_lists_name_user'
  ) THEN
    -- Index already exists; nothing to do.
    RAISE NOTICE '⚠️  Unique index idx_saved_lists_name_user already exists, skipping dedup';
  ELSE
    DELETE FROM public.saved_lists
    WHERE id NOT IN (
      SELECT MIN(id)
      FROM public.saved_lists
      GROUP BY name, user_id
    );
    RAISE NOTICE '✅ Deduplicated saved_lists rows';
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_saved_lists_name_user
  ON public.saved_lists(name, user_id);
CREATE INDEX IF NOT EXISTS idx_saved_lists_user_id
  ON public.saved_lists(user_id);

COMMENT ON TABLE public.saved_lists IS
'Custom song lists created by users. The "In Range" list is auto-created on first use.';

-- ============================================================================
-- TABLE: saved_songs
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.saved_songs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 300),
  artist TEXT NOT NULL CHECK (char_length(artist) BETWEEN 1 AND 200),
  vocal_range TEXT CHECK (vocal_range IS NULL OR char_length(vocal_range) <= 50),
  list_name TEXT NOT NULL CHECK (char_length(list_name) BETWEEN 1 AND 100),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_saved_songs_user_id ON public.saved_songs(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_songs_list_name ON public.saved_songs(list_name);
CREATE INDEX IF NOT EXISTS idx_saved_songs_name_artist
  ON public.saved_songs(name, artist);

COMMENT ON TABLE public.saved_songs IS
'Saved songs belonging to user lists. Each row references a list via list_name.';

-- ============================================================================
-- ROW LEVEL SECURITY — saved_lists
-- ============================================================================
ALTER TABLE public.saved_lists ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'saved_lists'
      AND policyname = 'Users can view their own lists'
  ) THEN
    CREATE POLICY "Users can view their own lists"
      ON public.saved_lists FOR SELECT
      TO public
      USING (user_id = auth.uid());

    RAISE NOTICE '✅ Created policy: Users can view their own lists';
  ELSE
    RAISE NOTICE '⚠️  Policy already exists: Users can view their own lists';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'saved_lists'
      AND policyname = 'Users can insert their own lists'
  ) THEN
    CREATE POLICY "Users can insert their own lists"
      ON public.saved_lists FOR INSERT
      TO public
      WITH CHECK (user_id = auth.uid());

    RAISE NOTICE '✅ Created policy: Users can insert their own lists';
  ELSE
    RAISE NOTICE '⚠️  Policy already exists: Users can insert their own lists';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'saved_lists'
      AND policyname = 'Users can update their own lists'
  ) THEN
    CREATE POLICY "Users can update their own lists"
      ON public.saved_lists FOR UPDATE
      TO public
      USING (user_id = auth.uid())
      WITH CHECK (user_id = auth.uid());

    RAISE NOTICE '✅ Created policy: Users can update their own lists';
  ELSE
    RAISE NOTICE '⚠️  Policy already exists: Users can update their own lists';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'saved_lists'
      AND policyname = 'Users can delete their own lists'
  ) THEN
    CREATE POLICY "Users can delete their own lists"
      ON public.saved_lists FOR DELETE
      TO public
      USING (user_id = auth.uid());

    RAISE NOTICE '✅ Created policy: Users can delete their own lists';
  ELSE
    RAISE NOTICE '⚠️  Policy already exists: Users can delete their own lists';
  END IF;
END $$;

-- ============================================================================
-- ROW LEVEL SECURITY — saved_songs
-- ============================================================================
ALTER TABLE public.saved_songs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'saved_songs'
      AND policyname = 'Users can view their own saved songs'
  ) THEN
    CREATE POLICY "Users can view their own saved songs"
      ON public.saved_songs FOR SELECT
      TO public
      USING (user_id = auth.uid());

    RAISE NOTICE '✅ Created policy: Users can view their own saved songs';
  ELSE
    RAISE NOTICE '⚠️  Policy already exists: Users can view their own saved songs';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'saved_songs'
      AND policyname = 'Users can insert their own saved songs'
  ) THEN
    CREATE POLICY "Users can insert their own saved songs"
      ON public.saved_songs FOR INSERT
      TO public
      WITH CHECK (user_id = auth.uid());

    RAISE NOTICE '✅ Created policy: Users can insert their own saved songs';
  ELSE
    RAISE NOTICE '⚠️  Policy already exists: Users can insert their own saved songs';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'saved_songs'
      AND policyname = 'Users can update their own saved songs'
  ) THEN
    CREATE POLICY "Users can update their own saved songs"
      ON public.saved_songs FOR UPDATE
      TO public
      USING (user_id = auth.uid())
      WITH CHECK (user_id = auth.uid());

    RAISE NOTICE '✅ Created policy: Users can update their own saved songs';
  ELSE
    RAISE NOTICE '⚠️  Policy already exists: Users can update their own saved songs';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'saved_songs'
      AND policyname = 'Users can delete their own saved songs'
  ) THEN
    CREATE POLICY "Users can delete their own saved songs"
      ON public.saved_songs FOR DELETE
      TO public
      USING (user_id = auth.uid());

    RAISE NOTICE '✅ Created policy: Users can delete their own saved songs';
  ELSE
    RAISE NOTICE '⚠️  Policy already exists: Users can delete their own saved songs';
  END IF;
END $$;

-- ============================================================================
-- ADMIN RPC: get most-saved songs across all users
-- ============================================================================
CREATE OR REPLACE FUNCTION public.admin_get_most_saved_songs()
RETURNS TABLE (
  song_name TEXT,
  artist TEXT,
  save_count BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
    SELECT ss.name::TEXT, ss.artist::TEXT, COUNT(*)::BIGINT AS save_count
    FROM public.saved_songs ss
    GROUP BY ss.name, ss.artist
    ORDER BY save_count DESC
    LIMIT 50;
END;
$$;
